language: python
python:
  - '2.7'

before_install:
  - 'travis_retry sudo apt-get update'
  - 'travis_retry sudo apt-get install python-dev libxml2-dev libxmlsec1-dev'
  - 'pip install -r requirements.txt'
  - 'pip install -r requirements-dev.txt'

script: 'echo "Done without specs" #mamba .'

deploy:
  provider: pypi
  user: gisce
  password:
    secure: pzc2ZAtW8Jp7PCUxWLz1/Jhrl0FTfdnHxnZz5mnxyqQBy1vR3BnYb/6mh79CmxjsWaUOS/bbhWlDUL6T8MDkT7825IPc/eIxiIhXbrqDOkyhBD08f2ghOJkJisB7WDxaaeyVx3+3p2qRwnwHjrjQsXiKk6r4VEJH8RNnS7KcYvrchTv2v6BLDGW7xEGpxY74tln4BE/sFVw2KFu50M+HBVMZ/GAEh9l2He2YCCh13/iVv/MndWUCR4W/OHpCKSGnMIq/iybpbynjrPNCOee8zkMUC3PlVLDkHtdmklTAMCyVMUY3vQCnGRpu2ZImNtzAPkXTnRnGtZfLInlIUC217ZC2hiZI/gls/fUqgWiRfBGVLfPTcNmRsm8Na3+cD4lWhLwclEvSJA/L/L6sCO+EjLKbE0KihZYY0W1sDH03ie9FmlfhVJxWJdBW+trfIYzEQ5jDa0rgm17FMPtM0dWr+gV35rp/AOquD2Axyf6JH/tvplz2IeUMMbGvz7CPLdut2iL0icvZARwDN2Wq3IrOiDpcdBwughuuK2fsjSKfEDyujJcc9atDujFvWtySRCrJUr3UMOJHs6lulLho6czM6gtMiqJhFTGDrGOwTRO36inKzVIdkRAic3aWdBtaq6a9lk32uJ+oibgCJle3n+8TkP7oSMYXSqRVrtU+jFzWGnc=
  on:
    tags: true
    repo: gisce/FACe-library
